package com.model;

/**
 * TDianpu generated by MyEclipse Persistence Tools
 */

public class TDianpu implements java.io.Serializable
{

	private Integer id;
	private String loginname;
	private String loginpw;
	private String mingcheng;
	
	private String zhuying;
	private String lianxiren;
	private String dianhua;
	private String tai;
	private String del;
	
	
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	public String getDianhua()
	{
		return dianhua;
	}
	public void setDianhua(String dianhua)
	{
		this.dianhua = dianhua;
	}
	public Integer getId()
	{
		return id;
	}
	
	public String getTai()
	{
		return tai;
	}
	public void setTai(String tai)
	{
		this.tai = tai;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getLianxiren()
	{
		return lianxiren;
	}
	public void setLianxiren(String lianxiren)
	{
		this.lianxiren = lianxiren;
	}
	public String getMingcheng()
	{
		return mingcheng;
	}
	
	public String getLoginname()
	{
		return loginname;
	}
	public void setLoginname(String loginname)
	{
		this.loginname = loginname;
	}
	public String getLoginpw()
	{
		return loginpw;
	}
	public void setLoginpw(String loginpw)
	{
		this.loginpw = loginpw;
	}
	public void setMingcheng(String mingcheng)
	{
		this.mingcheng = mingcheng;
	}
	public String getZhuying()
	{
		return zhuying;
	}
	public void setZhuying(String zhuying)
	{
		this.zhuying = zhuying;
	}

}